routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//auth routes
Route::get('/logout', 'QuickAuth\LogoutController@logout')->name('logout');

Route::post('/login', 'QuickAuth\LoginController@login')->name('login');

Route::middleware(['checkConnection'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::name('shop.')->group(function(){
        Route::get('/shop', 'ShopController@index')->name('index');
        Route::get('/shopList', 'ShopController@shopListGenerator')->name('shopList');
    });

    Route::name('shareFiles.')->group(function(){
        Route::get('/shareFiles', 'ShareFilesController@index')->name('index');
        Route::get('/download', 'ShareFilesController@download')->name('download');
    });

    Route::name('permission.')->group(function(){
        Route::get('/permission', 'PermissionController@index')->name('index');
        Route::put('permission/{id}', 'PermissionController@update')->name('update');
        Route::post('permission', 'PermissionController@create')->name('create');
        Route::delete('permission/{user}', 'PermissionController@delete')->name('delete');
    });
});

resources/views/LoggedHome.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">

        </div>
    </div>
</div>
@endsection

resources/views/error.blade.php
error :
@php
    echo $error;
@endphp

resources/views/home.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/home.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/home.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    @component('layouts.partials.popup')

    @endcomponent

    <div id="app-home">
        <app></app>
    </div>

</div>
</body>
</html>

resources/views/permission.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div id="permission-content" class="col-md-12">
            <div class="card">
                <div id="column-name">
                    <span>name</span>
                    <span>password</span>
                    <span>permission</span>
                    <span>actions</span>
                </div>
                @each('layouts.partials.user', $users, 'user')
                <div class="user-row" id="user-create">
                    @csrf
                    <div class="table-box">
                        <input type="text" name="name" value="">
                    </div>
                    <div class="table-box">
                        <input type="password" name="password" value="">
                    </div>
                    <div class="table-box">
                            <label>shop</label><input type="checkbox" name="permission.shop">
                            <label>download</label><input type="checkbox" name="permission.download">
                            <label>permission</label><input type="checkbox" name="permission.permission">
                            <label>shareFiles</label><input type="checkbox" name="permission.shareFiles">
                    </div>
                    <div class="crud-action table-box">
                        <span class="btn btn-create" data-url="{{ route('permission.create') }}">create</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

<script>

</script>

resources/views/shareFiles.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Files</div>
                <div id="file-list">
                    @foreach($files as $file)
                        @component('layouts.partials.file', ['file' => $file])
                        @endcomponent
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/shop.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div id="shop">
            <shop user-id="{{ $user->id }}" user-token="{{ $user->api_token }}"></shop>
        </div>
    </div>
@endsection

resources/views/shopListGenerator.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div id="shop-list-generator">
            <shop-list user-token="{{ $user->api_token }}"></shop-list>
        </div>
    </div>
@endsection