routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//auth routes
Route::get('/logout', 'QuickAuth\LogoutController@logout')->name('logout');

Route::post('/login', 'QuickAuth\LoginController@login')->name('login');

Route::middleware(['checkConnection'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::name('shop.')->group(function(){
        Route::get('/shop', 'ShopController@index')->name('index');
        Route::get('/shopList', 'ShopController@shopListGenerator')->name('shopList');
    });

    Route::name('shareFiles.')->group(function(){
        Route::get('/shareFiles', 'ShareFilesController@index')->name('index');
        Route::get('/download', 'ShareFilesController@download')->name('download');
    });

    Route::name('permission.')->group(function(){
        Route::get('/permission', 'PermissionController@index')->name('index');
        Route::put('permission/{id}', 'PermissionController@update')->name('update');
        Route::post('permission', 'PermissionController@create')->name('create');
        Route::delete('permission/{user}', 'PermissionController@delete')->name('delete');
    });
});

resources/views/layouts/partials/file.blade.php
<div class="file-list-element">
    <a href="{{route('shareFiles.download', ['name' => $file])}}">{{ $file }}</a>
</div>

resources/views/layouts/partials/popup.blade.php
<!-- The Modal -->
<div id="modal">

    <!-- Modal content -->
    <div class="modal-content container">
        <span class="close">&times;</span>
        <div>
            <form method="POST" action="{{ route('login') }}">
                @csrf
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" required autocomplete="name">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                    <div class="col-md-6">
                        <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password">


                    </div>
                </div>


                <div class="form-group row">
                    <div class="col-md-4 text-md-right">
                        <button type="submit" class="btn btn-primary">
                            {{ __('Login') }}
                        </button>
                    </div>
                    <div class="col-md-6 text-danger error-text"></div>
                </div>
            </form>
        </div>
    </div>

</div>

resources/views/layouts/partials/user.blade.php
<div class="user-row existing-user" id="user-{{ $user->id }}">
    @csrf
    <div class="table-box">
        <input type="text" name="name" value="{{$user->name}}">
    </div>
    <div class="table-box">
        <input type="password" name="password" value="">
    </div>
    <div class="table-box">
        @foreach($user->permissions as $name => $permission)
            <label>{{$name}}</label><input type="checkbox" name="permission.{{$name}}" @if($permission === true) checked @endif>
        @endforeach
    </div>
    <div class="crud-action table-box">
        <span class="btn btn-update" data-url="{{ route('permission.update', ['id' => $user->id]) }}" data-user-id="{{ $user->id }}">update</span>
        <span class="btn btn-delete" data-url="{{ route('permission.delete', ['user' => $user->id]) }}" data-user-id="{{ $user->id }}">delete</span>
    </div>
</div>