routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//auth routes
Route::get('/logout', 'QuickAuth\LogoutController@logout')->name('logout');

Route::post('/login', 'QuickAuth\LoginController@login')->name('login');

Route::middleware(['checkConnection'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::name('shop.')->group(function(){
        Route::get('/shop', 'ShopController@index')->name('index');
        Route::get('/shopList', 'ShopController@shopListGenerator')->name('shopList');
    });

    Route::name('shareFiles.')->group(function(){
        Route::get('/shareFiles', 'ShareFilesController@index')->name('index');
        Route::get('/download', 'ShareFilesController@download')->name('download');
    });

    Route::name('permission.')->group(function(){
        Route::get('/permission', 'PermissionController@index')->name('index');
        Route::put('permission/{id}', 'PermissionController@update')->name('update');
        Route::post('permission', 'PermissionController@create')->name('create');
        Route::delete('permission/{user}', 'PermissionController@delete')->name('delete');
    });
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        @component('layouts.nav', ['guest' => $guest])

        @endcomponent
        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <!-- Scripts -->
    <!-- app.js contain the general js stuff we need, every other one contain specific stuff by pages -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    @if(Request::url() == route('shop.index'))
        <script src="{{ asset('js/shop.js') }}" defer></script>
    @elseif(Request::url() == route('shop.shopList'))
        <script src="{{ asset('js/shopList.js') }}" defer></script>
    @elseif(Request::url() == route('permission.index'))
        <script src="{{ asset('js/permission.js') }}" defer></script>
    @endif
</body>
</html>

resources/views/layouts/nav.blade.php
@php
    switch (Request::url()){
        case(route('shareFiles.index')) :
            $mainColor = 'bg-title-red';
            break;
        case(route('shop.index')) :
            $mainColor = 'bg-title-darkorange';
            break;
        case(route('permission.index')) :
            $mainColor = 'bg-title-dodgerblue';
            break;
        default:
            $mainColor = 'bg-white';
            break;
    }
@endphp

<nav class="navbar navbar-expand-md navbar-light {{$mainColor}}">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @if($guest)
                    <li class="nav-item">
                        <span id="open-login">Login</span>
                    </li>
                @else
                    <li class="nav-item">
                        <a id="open-logout" href="{{ route('logout') }}">Logout</a>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>
<div id="menu">
    <ul class="container">
        @if(isset($permission->shareFiles) && $permission->shareFiles === true)
            @if(Request::url() !== route('shareFiles.index'))<a href="{{ route('shareFiles.index') }}"> @endif
                <li class="red-menu @if(Request::url() == route('shareFiles.index'))selected-menu @endif">file tools</li>
            @if(Request::url() !== route('shareFiles.index'))</a> @endif
        @endif

        @if(isset($permission->shop) && $permission->shop === true)
            @if(Request::url() !== route('shop.index'))<a href="{{ route('shop.index') }}"> @endif
                <li class="main-menu orange-menu @if(Request::url() == route('shop.index'))selected-menu @endif">shop tools</li>
            @if(Request::url() !== route('shop.index'))</a> @endif
        @endif

        @if(isset($permission->permission) && $permission->permission === true)
            @if(Request::url() !== route('permission.index'))<a href="{{ route('permission.index') }}"> @endif
                <li class="blue-menu @if(Request::url() == route('permission.index'))selected-menu @endif">permission manager</li>
            @if(Request::url() !== route('permission.index'))</a> @endif
        @endif
    </ul>
</div>